<a href="https://colab.research.google.com/github/Nevethawei/my-first-code/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

from google.colab import files
uploaded = files.upload()

Saving Car Sell Dataset intern.xlsx to Car Sell Dataset intern.xlsx

In [ ]:
import pandas as pd
data=pd.read_excel('Car Sell Dataset intern.xlsx')
print(data)

                Brand Model Name Model Variant   Car Type Transmission  \
0            Mahindra     TUV300           AX5        SUV       Manual
1               Skoda      Rapid         Style      Sedan       Manual
2       Maruti Suzuki       Alto             Z  Hatchback       Manual
3             Hyundai  Grand i10         Magna  Hatchback       Manual
4            Mahindra     XUV500            W8        SUV       Manual
...               ...        ...           ...        ...          ...
140899       Mahindra    Scorpio           W11        SUV       Manual
140900        Hyundai        i10           Era  Hatchback       Manual
140901          Honda       Jazz             V      Sedan    Automatic
140902          Honda       WR-V             E        SUV       Manual
140903      Chevrolet     Tavera          Base        MPV       Manual

       Fuel Type  Year  Kilometers Owner           State Accidental   Price
0            CNG  2017      164654   1st       Rajasthan         No  547253
1         Petrol  2018       41351   1st     Maharashtra         No  512050
2         Diesel  2002      119090  3rd+      Tamil Nadu         No  678923
3         Diesel  2013       19979   1st  Andhra Pradesh         No  522500
4         Petrol  2011      130591  3rd+           Bihar         No  401182
...          ...   ...         ...   ...             ...        ...     ...
140899    Petrol  2002       62699   1st       Telangana         No  221067
140900    Petrol  2013       47953   2nd     Maharashtra         No  745360
140901    Diesel  2009      134566  3rd+          Odisha         No  122852
140902    Diesel  2022       88697   1st         Gujarat         No  502425
140903    Diesel  2009       48117   2nd         Gujarat         No  905080

[140904 rows x 12 columns]

In [ ]:
data.head()

,Brand,Model Name,Model Variant,Car Type,Transmission,Fuel Type,Year,Kilometers,Owner,State,Accidental,Price
0,Mahindra,TUV300,AX5,SUV,Manual,CNG,2017,164654,1st,Rajasthan,No,547253
1,Skoda,Rapid,Style,Sedan,Manual,Petrol,2018,41351,1st,Maharashtra,No,512050
2,Maruti Suzuki,Alto,Z,Hatchback,Manual,Diesel,2002,119090,3rd+,Tamil Nadu,No,678923
3,Hyundai,Grand i10,Magna,Hatchback,Manual,Diesel,2013,19979,1st,Andhra Pradesh,No,522500
4,Mahindra,XUV500,W8,SUV,Manual,Petrol,2011,130591,3rd+,Bihar,No,401182

In [ ]:
data.tail()

,Brand,Model Name,Model Variant,Car Type,Transmission,Fuel Type,Year,Kilometers,Owner,State,Accidental,Price
140899,Mahindra,Scorpio,W11,SUV,Manual,Petrol,2002,62699,1st,Telangana,No,221067
140900,Hyundai,i10,Era,Hatchback,Manual,Petrol,2013,47953,2nd,Maharashtra,No,745360
140901,Honda,Jazz,V,Sedan,Automatic,Diesel,2009,134566,3rd+,Odisha,No,122852
140902,Honda,WR-V,E,SUV,Manual,Diesel,2022,88697,1st,Gujarat,No,502425
140903,Chevrolet,Tavera,Base,MPV,Manual,Diesel,2009,48117,2nd,Gujarat,No,905080

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140904 entries, 0 to 140903
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Brand          140904 non-null  object
 1   Model Name     140904 non-null  object
 2   Model Variant  140904 non-null  object
 3   Car Type       140904 non-null  object
 4   Transmission   140904 non-null  object
 5   Fuel Type      140904 non-null  object
 6   Year           140904 non-null  int64
 7   Kilometers     140904 non-null  int64
 8   Owner          140904 non-null  object
 9   State          140904 non-null  object
 10  Accidental     140904 non-null  object
 11  Price          140904 non-null  int64
dtypes: int64(3), object(9)
memory usage: 12.9+ MB

In [ ]:
data.describe()

                Year     Kilometers         Price
count  140904.000000  140904.000000  1.409040e+05
mean     2016.960391   95024.595987  7.617872e+05
std         5.106106   49133.157878  4.438578e+05
min      2000.000000   10000.000000  5.005500e+04
25%      2014.000000   52421.000000  4.116420e+05
50%      2018.000000   94973.500000  6.828030e+05
75%      2021.000000  137618.000000  1.034178e+06
max      2023.000000  179998.000000  2.744280e+06

from matplotlib import pyplot as plt
_df_0['Year'].plot(kind='hist', bins=20, title='Year')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Kilometers'].plot(kind='hist', bins=20, title='Kilometers')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Price'].plot(kind='hist', bins=20, title='Price')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3.plot(kind='scatter', x='Year', y='Kilometers', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='Kilometers', y='Price', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Year']
  ys = series['Kilometers']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_5.sort_values('Year', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Year')
_ = plt.ylabel('Kilometers')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Year']
  ys = series['Price']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_6.sort_values('Year', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Year')
_ = plt.ylabel('Price')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Year']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Year'}, axis=1)
              .sort_values('Year', ascending=True))
  xs = counted['Year']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_7.sort_values('Year', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Year')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_8['Year'].plot(kind='line', figsize=(8, 4), title='Year')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_9['Kilometers'].plot(kind='line', figsize=(8, 4), title='Kilometers')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['Price'].plot(kind='line', figsize=(8, 4), title='Price')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
data.isnull()

,Brand,Model Name,Model Variant,Car Type,Transmission,Fuel Type,Year,Kilometers,Owner,State,Accidental,Price
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
140899,False,False,False,False,False,False,False,False,False,False,False,False
140900,False,False,False,False,False,False,False,False,False,False,False,False
140901,False,False,False,False,False,False,False,False,False,False,False,False
140902,False,False,False,False,False,False,False,False,False,False,False,False
140903,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
data.dtypes

Brand            object
Model Name       object
Model Variant    object
Car Type         object
Transmission     object
Fuel Type        object
Year              int64
Kilometers        int64
Owner            object
State            object
Accidental       object
Price             int64
dtype: object

In [ ]:
data.shape

(140904, 12)

In [ ]:
data.columns

Index(['Brand', 'Model Name', 'Model Variant', 'Car Type', 'Transmission',
       'Fuel Type', 'Year', 'Kilometers', 'Owner', 'State', 'Accidental',
       'Price'],
      dtype='object')

In [ ]:
data['Model Variant'].value_counts()

Model Variant
V            14975
ZX           14896
Base         14199
L            10824
Z            10692
             ...
R-Dynamic      221
Portfolio      217
LTZ            196
LS             190
LT             169
Name: count, Length: 82, dtype: int64

In [ ]:
data.drop('Model Variant', axis=1)

,Brand,Model Name,Car Type,Transmission,Fuel Type,Year,Kilometers,Owner,State,Accidental,Price
0,Mahindra,TUV300,SUV,Manual,CNG,2017,164654,1st,Rajasthan,No,547253
1,Skoda,Rapid,Sedan,Manual,Petrol,2018,41351,1st,Maharashtra,No,512050
2,Maruti Suzuki,Alto,Hatchback,Manual,Diesel,2002,119090,3rd+,Tamil Nadu,No,678923
3,Hyundai,Grand i10,Hatchback,Manual,Diesel,2013,19979,1st,Andhra Pradesh,No,522500
4,Mahindra,XUV500,SUV,Manual,Petrol,2011,130591,3rd+,Bihar,No,401182
...,...,...,...,...,...,...,...,...,...,...,...
140899,Mahindra,Scorpio,SUV,Manual,Petrol,2002,62699,1st,Telangana,No,221067
140900,Hyundai,i10,Hatchback,Manual,Petrol,2013,47953,2nd,Maharashtra,No,745360
140901,Honda,Jazz,Sedan,Automatic,Diesel,2009,134566,3rd+,Odisha,No,122852
140902,Honda,WR-V,SUV,Manual,Diesel,2022,88697,1st,Gujarat,No,502425
140903,Chevrolet,Tavera,MPV,Manual,Diesel,2009,48117,2nd,Gujarat,No,905080

In [ ]:
data.drop(3)

,Brand,Model Name,Model Variant,Car Type,Transmission,Fuel Type,Year,Kilometers,Owner,State,Accidental,Price
0,Mahindra,TUV300,AX5,SUV,Manual,CNG,2017,164654,1st,Rajasthan,No,547253
1,Skoda,Rapid,Style,Sedan,Manual,Petrol,2018,41351,1st,Maharashtra,No,512050
2,Maruti Suzuki,Alto,Z,Hatchback,Manual,Diesel,2002,119090,3rd+,Tamil Nadu,No,678923
4,Mahindra,XUV500,W8,SUV,Manual,Petrol,2011,130591,3rd+,Bihar,No,401182
5,Maruti Suzuki,Dzire,Base,Sedan,Manual,Diesel,2019,71192,1st,Uttar Pradesh,No,219848
...,...,...,...,...,...,...,...,...,...,...,...,...
140899,Mahindra,Scorpio,W11,SUV,Manual,Petrol,2002,62699,1st,Telangana,No,221067
140900,Hyundai,i10,Era,Hatchback,Manual,Petrol,2013,47953,2nd,Maharashtra,No,745360
140901,Honda,Jazz,V,Sedan,Automatic,Diesel,2009,134566,3rd+,Odisha,No,122852
140902,Honda,WR-V,E,SUV,Manual,Diesel,2022,88697,1st,Gujarat,No,502425
140903,Chevrolet,Tavera,Base,MPV,Manual,Diesel,2009,48117,2nd,Gujarat,No,905080

In [ ]:
data.drop([3,4,5])

,Brand,Model Name,Model Variant,Car Type,Transmission,Fuel Type,Year,Kilometers,Owner,State,Accidental,Price
0,Mahindra,TUV300,AX5,SUV,Manual,CNG,2017,164654,1st,Rajasthan,No,547253
1,Skoda,Rapid,Style,Sedan,Manual,Petrol,2018,41351,1st,Maharashtra,No,512050
2,Maruti Suzuki,Alto,Z,Hatchback,Manual,Diesel,2002,119090,3rd+,Tamil Nadu,No,678923
6,MG,Hector,Smart,SUV,Manual,CNG,2023,61255,2nd,Maharashtra,No,1092070
7,Maruti Suzuki,Baleno,L,Hatchback,Manual,Diesel,2017,55072,1st,Gujarat,No,643104
...,...,...,...,...,...,...,...,...,...,...,...,...
140899,Mahindra,Scorpio,W11,SUV,Manual,Petrol,2002,62699,1st,Telangana,No,221067
140900,Hyundai,i10,Era,Hatchback,Manual,Petrol,2013,47953,2nd,Maharashtra,No,745360
140901,Honda,Jazz,V,Sedan,Automatic,Diesel,2009,134566,3rd+,Odisha,No,122852
140902,Honda,WR-V,E,SUV,Manual,Diesel,2022,88697,1st,Gujarat,No,502425
140903,Chevrolet,Tavera,Base,MPV,Manual,Diesel,2009,48117,2nd,Gujarat,No,905080